import {
  Journey,
  TrainSearchResult,
  Weather,
  ElevationData,
  NearbyGeography,
  RouteWeatherCheckpoint,
} from "@/types";

export const MOCK_TRAINS: TrainSearchResult[] = [
  {
    id: "20608",
    number: "20608",
    name: "Vande Bharat Express",
    type: "Vande Bharat",
    origin: { code: "MYS", name: "Mysuru Junction" },
    destination: { code: "MAS", name: "Mgr Chennai Central" },
    totalDistanceKm: 497,
    departureTime: "13:05",
    arrivalTime: "19:20",
    runningDays: ["Mon", "Tue", "Thu", "Fri", "Sat", "Sun"],
  },
  {
    id: "12951",
    number: "12951",
    name: "Mumbai Tejas Rajdhani",
    type: "Tejas Rajdhani",
    origin: { code: "MMCT", name: "Mumbai Central" },
    destination: { code: "NDLS", name: "New Delhi" },
    totalDistanceKm: 1386,
    departureTime: "17:00",
    arrivalTime: "08:32",
    runningDays: ["Daily"],
  },
  {
    id: "12002",
    number: "12002",
    name: "Bhopal Shatabdi Express",
    type: "Shatabdi Express",
    origin: { code: "NDLS", name: "New Delhi" },
    destination: { code: "RKMP", name: "Rani Kamlapati (Bhopal)" },
    totalDistanceKm: 702,
    departureTime: "06:00",
    arrivalTime: "14:40",
    runningDays: ["Daily"],
  },
  {
    id: "22436",
    number: "22436",
    name: "Vande Bharat Express",
    type: "Vande Bharat",
    origin: { code: "NDLS", name: "New Delhi" },
    destination: { code: "BSB", name: "Varanasi Junction" },
    totalDistanceKm: 759,
    departureTime: "06:00",
    arrivalTime: "14:00",
    runningDays: ["Tue", "Wed", "Fri", "Sat", "Sun"],
  },
  {
    id: "12245",
    number: "12245",
    name: "Howrah Yesvantpur Duronto",
    type: "Duronto Express",
    origin: { code: "HWH", name: "Howrah Junction" },
    destination: { code: "YPR", name: "Yesvantpur Junction" },
    totalDistanceKm: 1946,
    departureTime: "10:50",
    arrivalTime: "16:00",
    runningDays: ["Tue", "Wed", "Fri", "Sat", "Sun"],
  },
];

// Detailed Journey: 20608 Vande Bharat Express (Mysuru -> Chennai)
export const MOCK_JOURNEY_20608: Journey = {
  id: "20608-live",
  train: {
    id: "20608",
    number: "20608",
    name: "Vande Bharat Express",
    type: "Vande Bharat",
    origin: {
      id: "MYS",
      code: "MYS",
      name: "Mysuru Junction",
      city: "Mysuru",
      state: "Karnataka",
      latitude: 12.3168,
      longitude: 76.6496,
      elevationMeters: 763,
    },
    destination: {
      id: "MAS",
      code: "MAS",
      name: "Mgr Chennai Central",
      city: "Chennai",
      state: "Tamil Nadu",
      latitude: 13.0827,
      longitude: 80.2707,
      elevationMeters: 8,
    },
    totalDistanceKm: 497,
    scheduledDurationHours: 6.25,
  },
  serviceDate: "2026-08-18",
  origin: {
    id: "MYS",
    code: "MYS",
    name: "Mysuru Junction",
    city: "Mysuru",
    state: "Karnataka",
    latitude: 12.3168,
    longitude: 76.6496,
    elevationMeters: 763,
  },
  destination: {
    id: "MAS",
    code: "MAS",
    name: "Mgr Chennai Central",
    city: "Chennai",
    state: "Tamil Nadu",
    latitude: 13.0827,
    longitude: 80.2707,
    elevationMeters: 8,
  },
  stations: [
    {
      station: {
        id: "MYS",
        code: "MYS",
        name: "Mysuru Junction",
        city: "Mysuru",
        latitude: 12.3168,
        longitude: 76.6496,
        elevationMeters: 763,
      },
      sequence: 1,
      scheduledDeparture: "13:05",
      actualDeparture: "13:05",
      distanceFromOriginKm: 0,
      platform: "1",
      haltMinutes: 0,
      status: "PASSED",
      delayMinutes: 0,
    },
    {
      station: {
        id: "MYA",
        code: "MYA",
        name: "Mandya",
        city: "Mandya",
        latitude: 12.5244,
        longitude: 76.8958,
        elevationMeters: 703,
      },
      sequence: 2,
      scheduledArrival: "13:38",
      actualArrival: "13:38",
      scheduledDeparture: "13:40",
      actualDeparture: "13:40",
      distanceFromOriginKm: 45,
      platform: "3",
      haltMinutes: 2,
      status: "PASSED",
      delayMinutes: 0,
    },
    {
      station: {
        id: "SBC",
        code: "SBC",
        name: "KSR Bengaluru City",
        city: "Bengaluru",
        latitude: 12.9778,
        longitude: 77.5713,
        elevationMeters: 920,
      },
      sequence: 3,
      scheduledArrival: "14:45",
      actualArrival: "14:48",
      scheduledDeparture: "14:50",
      actualDeparture: "14:53",
      distanceFromOriginKm: 138,
      platform: "7",
      haltMinutes: 5,
      status: "PASSED",
      delayMinutes: 3,
    },
    {
      station: {
        id: "KJM",
        code: "KJM",
        name: "Krishnarajapuram",
        city: "Bengaluru",
        latitude: 12.9972,
        longitude: 77.6775,
        elevationMeters: 900,
      },
      sequence: 4,
      scheduledArrival: "15:08",
      actualArrival: "15:10",
      scheduledDeparture: "15:10",
      actualDeparture: "15:12",
      distanceFromOriginKm: 152,
      platform: "2",
      haltMinutes: 2,
      status: "PASSED",
      delayMinutes: 2,
    },
    {
      station: {
        id: "KPD",
        code: "KPD",
        name: "Katpadi Junction",
        city: "Vellore",
        latitude: 12.9698,
        longitude: 79.1367,
        elevationMeters: 215,
      },
      sequence: 5,
      scheduledArrival: "17:28",
      actualArrival: "17:34",
      scheduledDeparture: "17:30",
      actualDeparture: "17:36",
      distanceFromOriginKm: 367,
      platform: "2",
      haltMinutes: 2,
      status: "CURRENT",
      delayMinutes: 6,
    },
    {
      station: {
        id: "AJJ",
        code: "AJJ",
        name: "Arakkonam Junction",
        city: "Arakkonam",
        latitude: 13.0805,
        longitude: 79.6677,
        elevationMeters: 85,
      },
      sequence: 6,
      scheduledArrival: "18:23",
      actualArrival: "18:27",
      scheduledDeparture: "18:25",
      actualDeparture: "18:29",
      distanceFromOriginKm: 428,
      platform: "1",
      haltMinutes: 2,
      status: "UPCOMING",
      delayMinutes: 4,
    },
    {
      station: {
        id: "MAS",
        code: "MAS",
        name: "Mgr Chennai Central",
        city: "Chennai",
        latitude: 13.0827,
        longitude: 80.2707,
        elevationMeters: 8,
      },
      sequence: 7,
      scheduledArrival: "19:20",
      actualArrival: "19:25",
      distanceFromOriginKm: 497,
      platform: "2A",
      haltMinutes: 0,
      status: "UPCOMING",
      delayMinutes: 5,
    },
  ],
  route: {
    type: "FeatureCollection",
    features: [
      {
        type: "Feature",
        properties: {
          trainNumber: "20608",
          trainName: "Vande Bharat Express",
          totalDistanceKm: 497,
        },
        geometry: {
          type: "LineString",
          coordinates: [
            [76.6496, 12.3168], // Mysuru
            [76.712, 12.385],
            [76.812, 12.458],
            [76.8958, 12.5244], // Mandya
            [77.039, 12.604],
            [77.165, 12.721],   // Ramanagara
            [77.288, 12.825],   // Bidadi
            [77.412, 12.895],   // Kengeri
            [77.5713, 12.9778], // Bengaluru SBC
            [77.632, 12.991],   // Bengaluru Cantt
            [77.6775, 12.9972], // Krishnarajapuram
            [77.785, 13.011],   // Whitefield
            [77.962, 13.028],   // Malur
            [78.135, 13.004],   // Bangarapet
            [78.345, 12.892],   // Kuppam
            [78.582, 12.802],   // Jolarpettai
            [78.751, 12.864],   // Ambur
            [79.012, 12.923],   // Gudiyattam
            [79.1367, 12.9698], // Katpadi Jn
            [79.351, 13.012],   // Walajah Road
            [79.524, 13.048],   // Sholinghur
            [79.6677, 13.0805], // Arakkonam Jn
            [79.882, 13.115],   // Tiruvallur
            [80.052, 13.123],   // Avadi
            [80.174, 13.098],   // Perambur
            [80.2707, 13.0827], // Chennai Central
          ],
        },
      },
    ],
  },
  liveStatus: {
    journeyId: "20608-live",
    train: {
      id: "20608",
      number: "20608",
      name: "Vande Bharat Express",
      type: "Vande Bharat",
      origin: {
        id: "MYS",
        code: "MYS",
        name: "Mysuru Junction",
        latitude: 12.3168,
        longitude: 76.6496,
      },
      destination: {
        id: "MAS",
        code: "MAS",
        name: "Mgr Chennai Central",
        latitude: 13.0827,
        longitude: 80.2707,
      },
      totalDistanceKm: 497,
    },
    status: "DELAYED",
    delayMinutes: 6,
    position: {
      lat: 12.973,
      lng: 79.172, // Approaching Katpadi / leaving Katpadi
    },
    speedKmph: 118,
    headingDeg: 78,
    currentStation: {
      id: "KPD",
      code: "KPD",
      name: "Katpadi Junction",
      latitude: 12.9698,
      longitude: 79.1367,
    },
    nextStation: {
      id: "AJJ",
      code: "AJJ",
      name: "Arakkonam Junction",
      latitude: 13.0805,
      longitude: 79.6677,
    },
    lastPassedStation: {
      id: "KJM",
      code: "KJM",
      name: "Krishnarajapuram",
      latitude: 12.9972,
      longitude: 77.6775,
    },
    etaNextStation: "18:29",
    etaDestination: "19:25",
    distanceCoveredKm: 374,
    distanceRemainingKm: 123,
    completionPercentage: 75.2,
    updatedAt: new Date().toISOString(),
    isStale: false,
    statusMessage: "Departed Katpadi Junction (KPD) • Cruising at 118 km/h towards Arakkonam",
  },
};

// Detailed Journey: 12951 Mumbai Tejas Rajdhani (Mumbai -> Delhi)
export const MOCK_JOURNEY_12951: Journey = {
  id: "12951-live",
  train: {
    id: "12951",
    number: "12951",
    name: "Mumbai Tejas Rajdhani",
    type: "Tejas Rajdhani",
    origin: {
      id: "MMCT",
      code: "MMCT",
      name: "Mumbai Central",
      city: "Mumbai",
      state: "Maharashtra",
      latitude: 18.9696,
      longitude: 72.8193,
      elevationMeters: 10,
    },
    destination: {
      id: "NDLS",
      code: "NDLS",
      name: "New Delhi",
      city: "New Delhi",
      state: "Delhi",
      latitude: 28.6139,
      longitude: 77.209,
      elevationMeters: 216,
    },
    totalDistanceKm: 1386,
    scheduledDurationHours: 15.5,
  },
  serviceDate: "2026-08-18",
  origin: {
    id: "MMCT",
    code: "MMCT",
    name: "Mumbai Central",
    city: "Mumbai",
    state: "Maharashtra",
    latitude: 18.9696,
    longitude: 72.8193,
    elevationMeters: 10,
  },
  destination: {
    id: "NDLS",
    code: "NDLS",
    name: "New Delhi",
    city: "New Delhi",
    state: "Delhi",
    latitude: 28.6139,
    longitude: 77.209,
    elevationMeters: 216,
  },
  stations: [
    {
      station: {
        id: "MMCT",
        code: "MMCT",
        name: "Mumbai Central",
        latitude: 18.9696,
        longitude: 72.8193,
        elevationMeters: 10,
      },
      sequence: 1,
      scheduledDeparture: "17:00",
      actualDeparture: "17:00",
      distanceFromOriginKm: 0,
      platform: "5",
      haltMinutes: 0,
      status: "PASSED",
      delayMinutes: 0,
    },
    {
      station: {
        id: "BVI",
        code: "BVI",
        name: "Borivali",
        latitude: 19.2291,
        longitude: 72.8573,
        elevationMeters: 14,
      },
      sequence: 2,
      scheduledArrival: "17:22",
      actualArrival: "17:23",
      scheduledDeparture: "17:24",
      actualDeparture: "17:25",
      distanceFromOriginKm: 30,
      platform: "6",
      haltMinutes: 2,
      status: "PASSED",
      delayMinutes: 1,
    },
    {
      station: {
        id: "ST",
        code: "ST",
        name: "Surat",
        latitude: 21.1702,
        longitude: 72.8311,
        elevationMeters: 13,
      },
      sequence: 3,
      scheduledArrival: "19:43",
      actualArrival: "19:43",
      scheduledDeparture: "19:48",
      actualDeparture: "19:48",
      distanceFromOriginKm: 263,
      platform: "1",
      haltMinutes: 5,
      status: "PASSED",
      delayMinutes: 0,
    },
    {
      station: {
        id: "BRC",
        code: "BRC",
        name: "Vadodara Junction",
        latitude: 22.3072,
        longitude: 73.1812,
        elevationMeters: 36,
      },
      sequence: 4,
      scheduledArrival: "21:06",
      actualArrival: "21:06",
      scheduledDeparture: "21:16",
      actualDeparture: "21:16",
      distanceFromOriginKm: 392,
      platform: "2",
      haltMinutes: 10,
      status: "PASSED",
      delayMinutes: 0,
    },
    {
      station: {
        id: "RTM",
        code: "RTM",
        name: "Ratlam Junction",
        latitude: 23.3315,
        longitude: 75.0367,
        elevationMeters: 494,
      },
      sequence: 5,
      scheduledArrival: "00:25",
      actualArrival: "00:25",
      scheduledDeparture: "00:28",
      actualDeparture: "00:28",
      distanceFromOriginKm: 653,
      platform: "5",
      haltMinutes: 3,
      status: "CURRENT",
      delayMinutes: 0,
    },
    {
      station: {
        id: "KOTA",
        code: "KOTA",
        name: "Kota Junction",
        latitude: 25.1842,
        longitude: 75.8648,
        elevationMeters: 253,
      },
      sequence: 6,
      scheduledArrival: "03:15",
      actualArrival: "03:15",
      scheduledDeparture: "03:20",
      actualDeparture: "03:20",
      distanceFromOriginKm: 920,
      platform: "1",
      haltMinutes: 5,
      status: "UPCOMING",
      delayMinutes: 0,
    },
    {
      station: {
        id: "NDLS",
        code: "NDLS",
        name: "New Delhi",
        latitude: 28.6139,
        longitude: 77.209,
        elevationMeters: 216,
      },
      sequence: 7,
      scheduledArrival: "08:32",
      actualArrival: "08:32",
      distanceFromOriginKm: 1386,
      platform: "1",
      haltMinutes: 0,
      status: "UPCOMING",
      delayMinutes: 0,
    },
  ],
  route: {
    type: "FeatureCollection",
    features: [
      {
        type: "Feature",
        properties: {
          trainNumber: "12951",
          trainName: "Mumbai Tejas Rajdhani",
          totalDistanceKm: 1386,
        },
        geometry: {
          type: "LineString",
          coordinates: [
            [72.8193, 18.9696], // Mumbai Central
            [72.8573, 19.2291], // Borivali
            [72.784, 19.697],   // Palghar
            [72.763, 20.378],   // Vapi
            [72.912, 20.854],   // Navsari
            [72.8311, 21.1702], // Surat
            [72.982, 21.704],   // Bharuch
            [73.1812, 22.3072], // Vadodara
            [73.612, 22.753],   // Godhra
            [74.254, 22.842],   // Dahod
            [74.623, 23.012],   // Meghnagar
            [75.0367, 23.3315], // Ratlam Jn
            [75.312, 23.754],   // Nagda
            [75.642, 24.231],   // Shamgarh
            [75.824, 24.698],   // Ramganj Mandi
            [75.8648, 25.1842], // Kota Jn
            [76.354, 25.984],   // Sawai Madhopur
            [76.812, 26.685],   // Gangapur City
            [77.012, 26.985],   // Bayana
            [77.498, 27.218],   // Bharatpur
            [77.674, 27.492],   // Mathura Jn
            [77.318, 28.408],   // Faridabad
            [77.241, 28.588],   // Hazrat Nizamuddin
            [77.209, 28.6139],  // New Delhi
          ],
        },
      },
    ],
  },
  liveStatus: {
    journeyId: "12951-live",
    train: {
      id: "12951",
      number: "12951",
      name: "Mumbai Tejas Rajdhani",
      type: "Tejas Rajdhani",
      origin: {
        id: "MMCT",
        code: "MMCT",
        name: "Mumbai Central",
        latitude: 18.9696,
        longitude: 72.8193,
      },
      destination: {
        id: "NDLS",
        code: "NDLS",
        name: "New Delhi",
        latitude: 28.6139,
        longitude: 77.209,
      },
      totalDistanceKm: 1386,
    },
    status: "ON_TIME",
    delayMinutes: 0,
    position: {
      lat: 23.41,
      lng: 75.09,
    },
    speedKmph: 130,
    headingDeg: 32,
    currentStation: {
      id: "RTM",
      code: "RTM",
      name: "Ratlam Junction",
      latitude: 23.3315,
      longitude: 75.0367,
    },
    nextStation: {
      id: "KOTA",
      code: "KOTA",
      name: "Kota Junction",
      latitude: 25.1842,
      longitude: 75.8648,
    },
    lastPassedStation: {
      id: "BRC",
      code: "BRC",
      name: "Vadodara Junction",
      latitude: 22.3072,
      longitude: 73.1812,
    },
    etaNextStation: "03:15",
    etaDestination: "08:32",
    distanceCoveredKm: 672,
    distanceRemainingKm: 714,
    completionPercentage: 48.5,
    updatedAt: new Date().toISOString(),
    isStale: false,
    statusMessage: "Running On Time • Cruising through Malwa Plateau at 130 km/h",
  },
};

// Weather data for 20608
export const MOCK_WEATHER_20608: {
  currentStation: Weather;
  nextStation: Weather;
  destination: Weather;
  checkpoints: RouteWeatherCheckpoint[];
} = {
  currentStation: {
    temperature: 31,
    feelsLike: 35,
    humidity: 68,
    windSpeed: 14,
    rainProbability: 15,
    condition: "Partly Cloudy",
    conditionIcon: "partly-cloudy",
    locationName: "Katpadi (Vellore)",
    updatedAt: new Date().toISOString(),
  },
  nextStation: {
    temperature: 32,
    feelsLike: 37,
    humidity: 74,
    windSpeed: 11,
    rainProbability: 25,
    condition: "Humid & Warm",
    conditionIcon: "sunny",
    locationName: "Arakkonam",
    updatedAt: new Date().toISOString(),
  },
  destination: {
    temperature: 33,
    feelsLike: 39,
    humidity: 82,
    windSpeed: 18,
    rainProbability: 40,
    condition: "Coastal Breeze with Clouds",
    conditionIcon: "cloudy",
    locationName: "Chennai Central",
    updatedAt: new Date().toISOString(),
  },
  checkpoints: [
    {
      id: "chk-1",
      distanceKm: 0,
      stationName: "Mysuru",
      coordinates: { lat: 12.3168, lng: 76.6496 },
      weather: {
        temperature: 25,
        feelsLike: 26,
        humidity: 62,
        windSpeed: 8,
        rainProbability: 10,
        condition: "Pleasant",
        conditionIcon: "sunny",
        locationName: "Mysuru",
        updatedAt: new Date().toISOString(),
      },
    },
    {
      id: "chk-2",
      distanceKm: 138,
      stationName: "Bengaluru",
      coordinates: { lat: 12.9778, lng: 77.5713 },
      weather: {
        temperature: 27,
        feelsLike: 28,
        humidity: 58,
        windSpeed: 16,
        rainProbability: 20,
        condition: "Breezy & Mild",
        conditionIcon: "partly-cloudy",
        locationName: "Bengaluru",
        updatedAt: new Date().toISOString(),
      },
    },
    {
      id: "chk-3",
      distanceKm: 367,
      stationName: "Katpadi",
      coordinates: { lat: 12.9698, lng: 79.1367 },
      weather: {
        temperature: 31,
        feelsLike: 35,
        humidity: 68,
        windSpeed: 14,
        rainProbability: 15,
        condition: "Warm",
        conditionIcon: "sunny",
        locationName: "Katpadi",
        updatedAt: new Date().toISOString(),
      },
    },
    {
      id: "chk-4",
      distanceKm: 497,
      stationName: "Chennai",
      coordinates: { lat: 13.0827, lng: 80.2707 },
      weather: {
        temperature: 33,
        feelsLike: 39,
        humidity: 82,
        windSpeed: 18,
        rainProbability: 40,
        condition: "Humid",
        conditionIcon: "cloudy",
        locationName: "Chennai",
        updatedAt: new Date().toISOString(),
      },
    },
  ],
};

// Elevation Profile for 20608 (Deccan Plateau down to Coromandel Coast)
export const MOCK_ELEVATION_20608: ElevationData = {
  maxElevationMeters: 920,
  minElevationMeters: 8,
  currentElevationMeters: 215,
  elevationGainMeters: 180,
  profile: [
    { distanceKm: 0, elevationMeters: 763, stationName: "Mysuru" },
    { distanceKm: 45, elevationMeters: 703, stationName: "Mandya" },
    { distanceKm: 90, elevationMeters: 620, stationName: "Ramanagara" },
    { distanceKm: 138, elevationMeters: 920, stationName: "Bengaluru" },
    { distanceKm: 152, elevationMeters: 900, stationName: "K.R. Puram" },
    { distanceKm: 210, elevationMeters: 840, stationName: "Bangarapet" },
    { distanceKm: 285, elevationMeters: 550, stationName: "Kuppam Ghat" },
    { distanceKm: 320, elevationMeters: 360, stationName: "Jolarpettai" },
    { distanceKm: 367, elevationMeters: 215, stationName: "Katpadi" },
    { distanceKm: 428, elevationMeters: 85, stationName: "Arakkonam" },
    { distanceKm: 470, elevationMeters: 32, stationName: "Avadi" },
    { distanceKm: 497, elevationMeters: 8, stationName: "Chennai MAS" },
  ],
};

// Nearby Geography for 20608
export const MOCK_GEOGRAPHY_20608: NearbyGeography = {
  rivers: [
    {
      id: "riv-1",
      category: "river",
      name: "Palar River Basin",
      description: "Major river in Tamil Nadu, crossed between Gudiyattam and Katpadi",
      latitude: 12.924,
      longitude: 79.082,
      distanceFromTrainKm: 4.8,
    },
    {
      id: "riv-2",
      category: "river",
      name: "Cauvery River System",
      description: "Lifeline of Karnataka & TN, flows south of Mysuru-Mandya line",
      latitude: 12.418,
      longitude: 76.685,
      distanceFromTrainKm: 12.2,
    },
  ],
  mountains: [
    {
      id: "mnt-1",
      category: "ghat",
      name: "Javadi Hills & Eastern Ghats",
      description: "Scenic granite hills stretching across northern Tamil Nadu",
      latitude: 12.78,
      longitude: 78.95,
      distanceFromTrainKm: 18.5,
      elevationMeters: 1100,
    },
    {
      id: "mnt-2",
      category: "mountain",
      name: "Chamundi Hills",
      description: "Prominent hill overlooking Mysuru with historic temple",
      latitude: 12.274,
      longitude: 76.671,
      distanceFromTrainKm: 8.1,
      elevationMeters: 1048,
    },
  ],
  bridgesAndTunnels: [
    {
      id: "brg-1",
      category: "bridge",
      name: "Palar Railway Viaduct Bridge",
      description: "Historic 18-span steel girder railway bridge",
      latitude: 12.942,
      longitude: 79.112,
      distanceFromTrainKm: 2.1,
    },
    {
      id: "tnl-1",
      category: "tunnel",
      name: "Kuppam Descent Cuttings",
      description: "Deep rock railway cuttings descending from Karnataka plateau",
      latitude: 12.82,
      longitude: 78.48,
      distanceFromTrainKm: 65.0,
    },
  ],
  monumentsAndAttractions: [
    {
      id: "mon-1",
      category: "monument",
      name: "Vellore Fort & Jalakandeswarar Temple",
      description: "16th-century granite fort surrounded by a massive moat, 6km from Katpadi",
      latitude: 12.923,
      longitude: 79.132,
      distanceFromTrainKm: 5.4,
    },
    {
      id: "mon-2",
      category: "tourist_attraction",
      name: "Sripuram Golden Temple",
      description: "Spiritual park with temple coated in 1500kg pure gold",
      latitude: 12.871,
      longitude: 79.088,
      distanceFromTrainKm: 11.0,
    },
    {
      id: "mon-3",
      category: "monument",
      name: "Mysore Palace (Amba Vilas)",
      description: "Grand Indo-Saracenic royal residence of the Wadiyar dynasty",
      latitude: 12.305,
      longitude: 76.655,
      distanceFromTrainKm: 2.2,
    },
  ],
  cities: [
    {
      id: "cty-1",
      category: "city",
      name: "Vellore",
      description: "Major hub for healthcare (CMC) and historical fort city",
      latitude: 12.916,
      longitude: 79.132,
      distanceFromTrainKm: 5.8,
    },
    {
      id: "cty-2",
      category: "city",
      name: "Ranipet Industrial Hub",
      description: "Leather and engineering manufacturing city",
      latitude: 12.928,
      longitude: 79.332,
      distanceFromTrainKm: 21.0,
    },
  ],
};
